title: Il Quaderno della Prof
description: Questo sito è creato e gestito da Lucia Capurri e i contenuti presenti si intendono liberamente disponibili con licenza CC-BY-NC, a scopo didattico.
lang: it
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
version: "7.5"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
