title: Il vecchio Quaderno della Prof
description: Questo sito si è trasferito su ilquadernodellaprof.it.
lang: it
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
version: "11.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
